// Export API client
export { apiClient } from './client'

// Export services
export { authService } from './auth.service'
export { projectsService } from './projects.service'
export { usersService } from './users.service'
export { applicationsService } from './applications.service'
export { messagesService } from './messages.service'
export { skillsService } from './skills.service'
export { matchingService } from './matching.service'
export { notificationsService } from './notifications.service'
export { paymentsService } from './payments.service'
export { adminService } from './admin.service'
export { disputesService } from './disputes.service'
export { verificationService } from './verification.service'
export { templatesService } from './templates.service'
export { analyticsService } from './analytics.service'
export { milestonesService } from './milestones.service'
export { timeTrackingService } from './time-tracking.service'

// Export types
export type { AuthResponse, RegisterRequest, LoginRequest } from './auth.service'
export type { Project, CreateProjectRequest, ProjectSearchParams } from './projects.service'
export type { User, BusinessUser, TalentUser, UpdateProfileRequest } from './users.service'
export type { Application, CreateApplicationRequest, ApplicationSearchParams } from './applications.service'
export type { Message, Conversation, SendMessageRequest } from './messages.service'
export type { Skill, SkillCategory, SkillSearchParams } from './skills.service'
export type { TalentMatch, ProjectMatch, MatchingParams, MatchingPreferences } from './matching.service'
export type { Notification, NotificationPreferences } from './notifications.service'
export type { Payment, Receipt, TaxDocument } from './payments.service'
export type { AdminStats, ProjectMonitoring, UserMonitoring, DisputeCase } from './admin.service'
export type { Dispute, CreateDisputeRequest } from './disputes.service'
export type { EmailVerification, PhoneVerification, BusinessVerification, IdentityVerification } from './verification.service'
export type { MessageTemplate, CreateTemplateRequest } from './templates.service'
export type { QualityMetrics, PerformanceMetrics, BusinessIntelligence } from './analytics.service'
export type { Deliverable, MilestoneProgress, MilestoneTimeline } from './milestones.service'
export type { TimeEntry, TimesheetSummary, PaymentPeriod, BiweeklyPaymentRequest } from './time-tracking.service'
